version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: your_username
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database_name
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
